name: lncrawl

services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 6gb
    restart: unless-stopped
    ports:
      - "7900:7900"
      - "4444:4444"
    environment:
      - SE_VNC_PASSWORD=secret

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lncrawl
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: lncrawl
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: -ll server
    environment:
      - PYTHONUNBUFFERED=1
      - LNCRAWL_DATA_PATH=/data
      - SELENIUM_GRID=http://chrome:4444
      - DATABASE_URL=postgresql+psycopg://pguser:pgpass@postgres:5432/lncrawl
    volumes:
      - /dev/shm:/dev/shm
      - appdata:/data
    depends_on:
      - chrome
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
  appdata:
